# Generated by Django 2.2.2 on 2019-06-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('password', models.CharField(max_length=60, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('doctor_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('working_unit', models.CharField(max_length=30, verbose_name='从业单位')),
                ('working_num', models.CharField(max_length=30, verbose_name='工号')),
                ('working_title', models.CharField(max_length=30, verbose_name='职称')),
                ('resume', models.TextField(max_length=1000, verbose_name='简介')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('password', models.CharField(max_length=60, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('guardian_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('password', models.CharField(max_length=60, verbose_name='密码')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('patient_id', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('longitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='纬度')),
                ('heart_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='心率')),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True, verbose_name='血压')),
                ('step_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='步数')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=6, null=True, verbose_name='性别')),
                ('marriage', models.CharField(blank=True, choices=[('YES', '已婚'), ('NO', '未婚')], max_length=20, null=True, verbose_name='婚姻状况')),
                ('age', models.CharField(blank=True, max_length=6, verbose_name='年龄')),
                ('job', models.CharField(blank=True, max_length=200, null=True, verbose_name='工作')),
                ('nation', models.CharField(blank=True, max_length=20, null=True, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='住址')),
                ('main_illness', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要疾病')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('add_time', models.CharField(max_length=50, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='TreatShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_now', models.TextField(blank=True, max_length=1000, null=True, verbose_name='现今病情')),
                ('illness_past', models.TextField(blank=True, max_length=1000, null=True, verbose_name='以往病史')),
                ('sub_visit_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='复诊时间')),
                ('treatment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='治疗方案')),
                ('medicine', models.TextField(blank=True, max_length=1000, null=True, verbose_name='服药信息')),
                ('treat_time', models.CharField(max_length=200, verbose_name='治疗时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor', verbose_name='医生身份证号')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Guardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='users.Patient', verbose_name='病人身份证号')),
            ],
            options={
                'db_table': 'treatShip',
                'unique_together': {('patient', 'doctor', 'guardian', 'treat_time')},
            },
        ),
        migrations.CreateModel(
            name='GuardianShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_time', models.CharField(max_length=30, null=True, verbose_name='监护时间')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Guardian', verbose_name='监护人身份证号')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='病人身份证号')),
            ],
            options={
                'db_table': 'guardianShip',
            },
        ),
        migrations.AddField(
            model_name='guardian',
            name='cares',
            field=models.ManyToManyField(related_name='carers', through='users.GuardianShip', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', through='users.TreatShip', to='users.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('working_unit', 'working_num')},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.CharField(max_length=50, verbose_name='预约时间')),
                ('appointment_state', models.CharField(choices=[('appoint', '预约'), ('completed', '已完成')], max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Doctor')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Guardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
            ],
            options={
                'db_table': 'appointment',
                'unique_together': {('patient', 'doctor', 'guardian', 'appointment_time')},
            },
        ),
    ]
